version: 2.1
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm i
            npm run build

      - save_cache:
          key: frontend-build
          paths:
            - frontend/node_modules

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: frontend-build

      - run:
          name: Test front-end
          command: |
            cd frontend
            npm i
            npm run test

workflows:
  default:
    jobs:
      - build-frontend
      - test-frontend:
          requires: [build-frontend]
